server:
  port: 3030

#spring:
#  cloud:
#    gateway:
#      routes:
spring:
  cloud:
    gateway:
      routes:
        -   id: order-service
            uri: http://localhost:2020
            predicates:
              - Path=/azure/**
            filters:
              - RewritePath=/azure/(?<path>.*),/$\{path}
